# Import dependencies

In [1]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.cluster import KMeans, AffinityPropagation
import warnings
#warnings.filterwarnings("ignore")
import numpy as np

import torch
from torch.utils.tensorboard import SummaryWriter

from utils import clustering_classification, test_classifier, write, save_metrics_to_dict, encode_categorical_features, import_dataset, agg_clustering, writer_add_scalars

# For logging 

In [2]:
writer = SummaryWriter(log_dir="C:\\awilde\\britta\\LTU\\AppliedAI\\runs")
#writer = SummaryWriter()
metrics_dict={
"train_acc_dict" : {},
"train_f1_dict" : {},
"test_acc_dict" : {},
"test_f1_dict" : {},
"train_acc_avg" : {},
"train_f1_avg" : {},
"test_acc_avg" : {},
"test_f1_avg" : {},
}

In [3]:
# Launch tensorboard
# images=21 change this to how many datasets you use
%tensorboard --logdir runs/ --port 6006 --samples_per_plugin images=22
# If in use (Mac) use to find the process PID
% lsof -i :6006
# Kill the process with 
% kill -9 <PID>
# Then launch using bash with first command

UsageError: Line magic function `%tensorboard` not found.


# Config Params

In [4]:
TEST_SIZE = 0.2
RANDOM_SEEDS = [41, 42, 43, 44, 45]
K_FOLDS = 5

# Our chosen datasets
TODO
We have chosen the datasets based on the following criteria:
- datasets where we do not need to do any special preprocessing so that it is easy to do in only one pipeline
- rather small datasets to ensure we do not need high computational power

In [5]:
# Dataset that seems useful
dataset_id = {
    # "iris": 53, 
    # "heart_disease": 45, 
    # "wine_quality": 186, 
    # "breast_cancer_wisconsin_diagnostic": 17, 
    # "car_evaluation": 19, 
    # "spect_heart" : 95, 
    # "spectf_heart" : 96,
    # "mushroom": 73, 
    # "statlog" : 144, 
    # "credit_approval" : 27, 
    # "zoo" : 111, 
    # "balance_scale" : 12, 
    # "ilpd" : 225, 
    # "acute_inflamations" : 184, 
    # "ecoli" : 39, 
    "mammographic_mass" : 161, 
    # "hayes_roth" : 44, 
    # "habermans_survival" : 43, 
    # "congress_voting_records" : 105, 
    # "balloons" : 13, 
    # "lenses" : 58, 
    # "fertility" : 244, 
}

# sort alphabetically and adds id for logging
data_set_sorted = {}
for i, name in enumerate(sorted(dataset_id.keys())):
    data_set_sorted[name] = (dataset_id[name], i+1)

print(data_set_sorted)

{'mammographic_mass': (161, 1)}


# Import and preprocess datasets
For the preprocessing we will do the following steps:
1. Remove any missing values. In the article the following is written: "Given that our classifiers are not oriented to data with missing features, the missing inputs are treated as zero, which should not bias the comparison results." We therefore also decided to just remove missing values and to more focus on the full pipeline instead of single datasets. Another way could have been interpolation.
2. Encode categorical data into numerical data. This we have to do to use the classifiers later on.
3. Remove certain columns if they are highly correlated to others. <span style="color: red;">ALERT!</span>
4. Split the data into a train and a test set. We will use a 80/20 split.
5. Scale the data so that we have zero mean and standard deviation of one. This is done with the Standard scaler.

# Testing different classifiers

## K-Nearest Neighbor classifier

In [6]:
# https://towardsdatascience.com/gridsearchcv-for-beginners-db48a90114ee
knn_params = [{'knn__n_neighbors': [3, 5, 7, 9],
        'knn__weights': ['uniform', 'distance'],
        'knn__leaf_size': [15, 20]}]

## Support vector machine classifier

In [7]:
# params taken from here: https://www.geeksforgeeks.org/svm-hyperparameter-tuning-using-gridsearchcv-ml/
svm_params = [{'svm__C': [0.1, 1, 10, 100, 1000],  
        'svm__gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
        'svm__kernel': ['rbf']} ]

## Logistic regression classifier

In [8]:
# params taken from here: https://www.geeksforgeeks.org/how-to-optimize-logistic-regression-performance/
# and from here https://www.kaggle.com/code/enespolat/grid-search-with-logistic-regression
log_reg_params = [
    {'log_reg__penalty':['l1','l2'],
    'log_reg__C' : np.logspace(-3,3,7),
    'log_reg__max_iter'  : [100,1000,2500,5000]
}
]

## Random Forest classifier

In [9]:
# https://www.datacamp.com/tutorial/random-forests-classifier-python
random_forest_params = [
    {"random_forest__n_estimators": [100, 500],
     "random_forest__max_depth" : [5, 10, 15]
}
]

## Gaussian naive bayes classifier

In [10]:
# https://www.kaggle.com/code/akshaysharma001/naive-bayes-with-hyperpameter-tuning#Hyperparameter-Tuning-to-improve-Accuracy
gnb_params = [
    {'gnb__var_smoothing': np.logspace(0,-9, num=10)
    }
]

## K-means unsupervised classifier

In [11]:
# Already use k-means++ and we set the no. clusters to no. of labels
# Set params in loop
kmeans_params = []

## Affinity propagation unsupervised classifier

In [12]:
# https://letsdatascience.com/affinity-propagation-clustering/
affinity_propagation_params = [
    # {"damping": [0.5, 0.7]}, 
    # #{"preference": [-50,-10,0,10,50]},
    # {"max_iter": [10000]}
    {"damping": [0.5, 0.7]}, 
    {"preference": [-50,-10,0,10,50]}
          ]

# Train test loop

In [13]:
for i, (name, id) in enumerate(data_set_sorted.items()):
        print("\n" + "#"*100)
        print(f"Current dataset: {name}")
        ordinal_encoder = OrdinalEncoder()

        # Set up dataset
        X, y = import_dataset(dataset_id[name], ordinal_encoder)
        labels = np.unique(y)
        y = encode_categorical_features(y, ordinal_encoder)
        print(f"Dataset size: {len(X)}")
        print(f"Labels in dataset: {labels}")
        print("#"*100, end="\n\n")


        for RANDOM_SEED in RANDOM_SEEDS:   

                print("*"*100)
                print("Current seed:", RANDOM_SEED)
                print("*"*100, end="\n\n")

                # split the dataset
                X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, random_state=RANDOM_SEED, stratify = y)

                # # KNN
                # clf_name = "knn"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # # https://towardsdatascience.com/gridsearchcv-for-beginners-db48a90114ee
                # knn = KNeighborsClassifier()
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = test_classifier(knn, clf_name, knn_params, X_train, y_train, X_test, y_test)

                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )

                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )
                
                # # SVM 
                # svm = SVC()
                # clf_name = "svm"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = test_classifier(svm, clf_name, svm_params, X_train, y_train, X_test, y_test)
                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )

                # # Logistic regression
                # log_reg = LogisticRegression()
                # clf_name = "log_reg"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = test_classifier(log_reg, 
                #                                                                         clf_name, 
                #                                                                         log_reg_params, 
                #                                                                         X_train, 
                #                                                                         y_train, 
                #                                                                         X_test, 
                #                                                                         y_test)
                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )
                
                # # Random forest
                # random_forest = RandomForestClassifier()
                # clf_name = "random_forest"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = test_classifier(random_forest, 
                #                                                                         clf_name, 
                #                                                                         random_forest_params, 
                #                                                                         X_train, 
                #                                                                         y_train, 
                #                                                                         X_test, 
                #                                                                         y_test)
                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )
                
                # # Gaussian naive bayes
                # gnb = GaussianNB()
                # clf_name = "gnb"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = test_classifier(gnb, 
                #                                                                         clf_name, 
                #                                                                         gnb_params, 
                #                                                                         X_train, 
                #                                                                         y_train, 
                #                                                                         X_test, 
                #                                                                         y_test)
                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )
                
        
                # # K-means
                # clf_name = "kmeans"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # kmeans_params = [{"algorithm": ["lloyd", "elkan"]}]
                # n_clusters = len(labels)
                # kmeans_params.append({"n_clusters": [n_clusters]})
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = clustering_classification(KMeans, clf_name, kmeans_params, X_train, y_train, X_test, y_test, RANDOM_SEED, K_FOLDS)
                # write(writer, name, clf_name, cm_train, "train", id[1])
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )

                # # Agglomerative clustering
                # clf_name = "agglomerative_clustering"
                # print("_"*100)
                # print(f"Classifier: {clf_name}")
                # train_acc, train_f1, test_acc, test_f1, cm_train, cm_test = agg_clustering(X_train, y_train, X_test, y_test, RANDOM_SEED)
                # write(writer, name, clf_name, cm_train, "train", id[1] )
                # write(writer, name, clf_name, cm_test, "test", id[1] )
                # metrics_dict = save_metrics_to_dict(clf_name,
                #                                 train_acc, 
                #                                 train_f1, 
                #                                 test_acc, 
                #                                 test_f1, 
                #                                 metrics_dict,
                #                                 i,
                #                                 RANDOM_SEED
                #                                 )
                

                # Affinity propagation
                clf_name = "affinity_propagation"
                print("_"*100)
                print(f"Classifier: {clf_name}")
                train_acc, train_f1, test_acc, test_f1, cm_train, cm_test =  clustering_classification(AffinityPropagation, clf_name, affinity_propagation_params, X_train, y_train, X_test, y_test, RANDOM_SEED, K_FOLDS)
                write(writer, name, clf_name, cm_train, "train", id[1] )
                write(writer, name, clf_name, cm_test, "test", id[1] )
                metrics_dict = save_metrics_to_dict(clf_name,
                                                train_acc, 
                                                train_f1, 
                                                test_acc, 
                                                test_f1, 
                                                metrics_dict,
                                                i,
                                                RANDOM_SEED
                                                )

        # Take average
        keys_to_update = ["train_acc_dict", "test_acc_dict", "train_f1_dict", "test_f1_dict"]
        for key in keys_to_update:
                metrics_dict[key] = {k: v / len(RANDOM_SEEDS) for k, v in metrics_dict[key].items()}
        # Write metrics to tensorboard, step is dataset id      
        writer.add_scalars("Train accuracy", metrics_dict["train_acc_dict"], id[1])
        writer.add_scalars("Test accuracy", metrics_dict["test_acc_dict"], id[1])
        writer.add_scalars("Train f1",  metrics_dict["train_f1_dict"], id[1])
        writer.add_scalars("Test f1", metrics_dict["test_f1_dict"], id[1])

        writer_add_scalars("Train average accuracy", writer, metrics_dict["train_acc_avg"], id[1])
        writer_add_scalars("Test average accuracy", writer, metrics_dict["test_acc_avg"], id[1])
        writer_add_scalars("Train average f1", writer, metrics_dict["train_f1_avg"], id[1])
        writer_add_scalars("Test average f1", writer, metrics_dict["test_f1_avg"], id[1])
        
        # reset dictionaries
        keys_to_update = ["train_acc_dict", "test_acc_dict", "train_f1_dict", "test_f1_dict"]
        for key in keys_to_update:
                metrics_dict[key] = {}
        

writer.close()


####################################################################################################
Current dataset: mammographic_mass
Dataset size: 830
Labels in dataset: [0 1]
####################################################################################################

****************************************************************************************************
Current seed: 41
****************************************************************************************************

____________________________________________________________________________________________________
Classifier: affinity_propagation
41
41
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 16 17 21 22 23 24 25 26 28 29
 32 33 34 36 39 42 43 45 47 48 55 58 59 60 62 63 64 66 68 70 74 77 79]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(14

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7 8 9]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)])
valid_clusters: [0 7 6 4 5 6 0 0 0 0 9 6 1 4 3 9 6 1 6 6 4 1 5 1 4 0 6 6 1 2 4 5 9 6 5 4 1
 2 4 1 2 5 1 1 4 4 4 1 7 4 3 5 4 7 1 6 5 4 5 0 0 0 1 0 6 6 1 0 4 4 4 4 4 6
 6 4 4 4 1 9 3 6 4 6 4 1 0 5 0 0 6 6 0 5 4 6 0 5 5 5 4 0 4 5 4 5 1 4 1 9 7
 1 6 6 8 0 9 6 6 5 0 0 3 0 7 4 6 6 6 1 4 4 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 20 21]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(20), np.int64(21)])
valid_clusters: [ 4  6 14 16  1  2  1  0 17 16  2  2 14 14  4  2  1  6  4 18 14 18 14  2
  6  6  6  6  4  6  6  1 17  1  6  2  7  1 20  1  6 14  1 1

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)])
valid_clusters: [6 2 3 6 2 3 6 3 1 5 2 2 3 2 2 6 5 6 6 5 2 6 0 2 2 5 0 5 1 1 6 3 2 2 2 0 0
 2 6 0 2 6 5 2 5 2 4 1 5 1 5 4 1 1 1 6 5 5 0 5 1 1 0 6 1 1 1 2 2 6 6 1 2 1
 6 3 2 5 1 5 1 0 2 5 1 2 2 0 2 0 4 0 6 2 2 5 1 2 6 6 5 2 1 1 1 6 3 5 5 1 6
 5 2 2 2 6 6 2 6 2 6 2 5 6 2 2 6 2 6 2 3 1 1]
[ 0  1  2  3  4  5  6  8 10 11 12 14 17 18 19 21 22 24 25 26 28 29 32 33
 36 40 41 42 44 47 49 51 52 54 55 57 60 62]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(14), np.int64(17), np.int64(18), np.int64(19), np.int64(21), np.int64(22), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(29), np.int64(32), np.int64(33), np.int64(36), np.int64(40), np.int64(41), np.int64(42), np.int64(44), np.int64(47),

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7 8 9]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)])
valid_clusters: [3 1 2 8 0 4 7 7 0 4 0 8 0 3 5 4 0 7 4 2 4 7 8 2 4 8 8 5 3 2 6 8 1 0 7 1 4
 5 7 4 1 4 2 4 2 0 2 5 8 8 1 2 7 8 8 4 8 7 4 4 2 5 4 5 3 8 4 8 8 6 3 8 2 3
 0 8 7 0 2 1 2 5 8 1 1 2 3 1 4 2 7 1 0 4 8 8 5 8 8 6 5 8 4 8 4 2 3 2 2 5 5
 2 8 4 4 8 3 4 1 5 1 6 4 1 3 1 4 8 0 8 1 7 5]
[0 1 2 3 4 5 6 7 8 9]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)])
valid_clusters: [0 7 2 4 0 2 6 6 6 0 9 2 4 4 3 9 5 5 2 2 4 5 0 5 6 0 2 2 5 1 4 6 9 2 0 4 5
 1 4 5 1 0 5 5 4 4 4 5 7 4 3 0 4 7 5 2 0 4 0 6 6 6 5 0 2 2 5 6 4 4 4 4 4 2
 2 6 4 4 5 9 3 2 4 2 4 5 6 0 6 6 2 2 6 6 4 2 0 0 6 6 4 6 4 0 4 6 5 6 5 9 7
 5 5 2 8 6 9 2 2 0 6 0 3 0 0 4 2 5 2 5 4 4 6]
[ 0  1  2  3  4  5  6  7  8  9 10]
labels_map_cv keys: dic

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 20 21 23 24 26 27
 28 29 30 32 34 35 37 40 41 42 46 47 48 49 51 52 54 55 57 62 63 64 65 67
 70 75 77 83 85 87]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(20), np.int64(21), np.int64(23), np.int64(24), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(32), np.int64(34), np.int64(35), np.int64(37), np.int64(40), np.int64(41), np.int64(42), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(51), np.int64(52), np.int64(54), np.int64(55), np.int64(57), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(67), np.int64(70), np.int64(75), np.int64(77), np.int64(83), np.int64(85), np.int64(87)])
valid_clusters: [ 0 48 32 57 12 67  2 63 55  3  1 16 32 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22)])
valid_clusters: [ 8 20 15 14  1  9 15 19  9 20 11 16 12 13  9 10 14  3 15 12  3 10  5  4
 20 10  0  0  3 15 15 10  9 20  2  5 14 10  0 15 20  3  3  1  3  9 14 14
 21 20 13 16  2  3 15  3  4  1 11 19 11  4 15 10 11 12  4  4 13 14  9 20
  1  1 20 20 11  9 19 10 11  3 14  1  4  2  1 20 12 21  2  4  5  2  4 13
 14  5  0 13 19 10  3  4 13  5  5 14 15 11 15 10 16  9  3  2 11  2 14 15
 11  9  4 16 20  4 20 15 19  2  4 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  47  48  49  50  51  52  53  54  55
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 107 108 109 110 111 112 113
 114 116 118 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 153
 154 155 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 180 183 184 185 186 187 188 191 192 193 195 197 199
 200 201 202 203 204 205 206 207 208 209 210 212 213 215 216 218 219 220
 221 223 224 225 226 228 229 230 231 232 233 234 235 236 237 239 240 241
 242 243 245 246 248 249 250 252 253 254 255 256 257 258 259 260 261 262
 263 265 266 267 269 270 271 272 273 274 275 276 27

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  25  26  27  28  29  30  31  32  35  36  37  38
  39  40  41  42  43  44  45  46  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  79  80  81  82  83  84  85  86  87  88  89  90  91  92  94  95
  96  97  98  99 101 102 103 106 107 108 109 111 112 113 114 115 116 117
 118 119 120 121 122 123 125 126 128 130 131 132 133 134 136 137 138 139
 140 142 143 144 145 146 147 148 149 150 151 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 180 182 183 185 186 187 188 189 190 191 192 194 195 197 198 199 200
 201 203 204 205 206 207 208 209 210 211 212 213 214 215 216 218 219 220
 221 223 224 226 227 228 229 230 231 232 234 235 236 237 238 239 240 243
 244 247 248 249 250 251 252 253 254 255 257 258 259 261 262 263 264 266
 267 268 269 270 271 272 274 275 276 277 278 279 28

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  45  46  47  48  49  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  94
  95  96  97  98  99 100 101 102 104 105 106 107 108 109 110 111 112 113
 114 115 116 118 119 120 121 122 123 124 125 126 127 128 129 130 131 133
 134 135 136 138 139 141 142 143 145 146 147 150 151 152 153 154 157 158
 159 160 161 162 163 164 165 166 168 170 171 172 173 174 175 176 177 179
 180 183 184 185 186 187 188 189 190 191 192 194 195 196 198 200 202 203
 204 205 206 207 208 209 210 213 214 216 217 218 219 220 221 222 223 224
 225 226 227 228 230 232 233 234 235 236 239 240 244 245 246 247 248 249
 250 251 252 253 254 255 257 258 259 262 263 264 265 266 267 268 269 270
 271 272 273 274 276 277 278 279 281 282 284 285 28

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  45  46  47  48  49  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  94
  95  96  97  98  99 100 101 102 104 105 106 107 108 109 110 111 112 113
 114 115 116 118 119 120 121 122 123 124 125 126 127 128 129 130 131 133
 134 135 136 138 139 141 142 143 145 146 147 150 151 152 153 154 157 158
 159 160 161 162 163 164 165 166 168 170 171 172 173 174 175 176 177 179
 180 183 184 185 186 187 188 189 190 191 192 194 195 196 198 200 202 203
 204 205 206 207 208 209 210 213 214 216 217 218 219 220 221 222 223 224
 225 226 227 228 230 232 233 234 235 236 239 240 244 245 246 247 248 249
 250 251 252 253 254 255 257 258 259 262 263 264 265 266 267 268 269 270
 271 272 273 274 276 277 278 279 281 282 284 285 28

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7 8]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)])
valid_clusters: [6 4 2 1 6 1 5 6 4 6 0 8 5 0 4 0 0 0 6 6 1 4 6 3 4 8 1 6 4 4 6 6 3 6 0 1 0
 4 0 4 1 1 0 1 1 4 0 0 0 6 0 8 4 4 4 4 0 6 0 1 0 0 2 5 3 1 4 0 1 4 6 0 0 6
 1 0 0 0 4 0 6 5 1 4 6 0 1 8 4 3 1 0 4 6 0 6 4 1 0 6 4 4 6 4 6 4 6 8 8 1 4
 5 6 4 1 6 0 0 0 4 1 3 0 4 1 0 4 3 0 0 0 6 5]
[0 1 2 3 4 5 6 7 8]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)])
valid_clusters: [1 2 1 3 6 1 6 4 5 1 2 6 5 1 0 5 3 1 6 3 5 5 5 6 6 5 3 5 7 0 5 2 1 3 0 5 2
 3 6 1 4 6 5 0 2 1 0 0 5 6 2 5 2 6 6 6 2 3 0 6 2 6 5 2 2 5 2 0 3 1 2 2 5 3
 7 2 3 3 1 2 3 1 5 7 5 2 5 0 2 0 2 5 0 5 5 6 2 5 8 5 5 5 5 5 1 1 5 5 6 5 7
 6 0 7 6 1 3 4 1 0 3 0 5 6 0 2 2 2 2 1 2 2 6]
[0 1 2 3 4 5 6 7 8]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2)

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7 10 11 15 16 17 18 19 20 21 22 24 25 26 28 30 31
 32 34 36 38 39 40 42 44]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(10), np.int64(11), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(30), np.int64(31), np.int64(32), np.int64(34), np.int64(36), np.int64(38), np.int64(39), np.int64(40), np.int64(42), np.int64(44)])
valid_clusters: [42 42  0 38 36  4 38  0 36  0 42 36 38  4 34 16 16 15 38  6 24 34 24 42
 42  6 16 42  5 42 16  0 38 42  0 34  7 36 36 42  2 42 16 16 36 32 38 34
 38 18 36 24 16 24 42 36 24 34 24 32  1 42 24 17 24 16 38  6 42 24 24  6
 36 24 36 16 42 42 18 42 42  6 42 34 24 42 36 15 15 42 16 42 16 42 24 15
 24 42 42 36 36 36 24 32 18 36 36 42 31 42  5 36 42 16 15 25  6  2 36 38
  0 15 11 10 24 24 16 38 42 26 20 42  2]
[0 1 2 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 17 18 19 20 21 22 23 26 27
 29 30 32 33 35 37 42 43 44 50 51 52 53 54]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(26), np.int64(27), np.int64(29), np.int64(30), np.int64(32), np.int64(33), np.int64(35), np.int64(37), np.int64(42), np.int64(43), np.int64(44), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54)])
valid_clusters: [26 18 15 27 26 27 17 26  4 44 42 52 33 42 18 42 21 35 26 29 27  8 29  2
 11 23 22 26  8 51 26 44  2 26  7  3 35 20 42 51 18 27 35  3 22  8  7 42
 35 21 21 52 51 19  8 12 35 26 35  3 42 42 15 50  2  3  6 42  3 13 26 42
 35 44 27 21 21 35 18  7 29 17 22 51 26  7 27 52 32 17 22 42 10 26 35 44
 19 27 35 42  8 13 2

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 18 19 20 21 23 24 25 26
 27 29 30 31 34 35 38 39 40 43 48 51 52 54 60 61 62 63 65 67 68 69 74 75
 79 80]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(29), np.int64(30), np.int64(31), np.int64(34), np.int64(35), np.int64(38), np.int64(39), np.int64(40), np.int64(43), np.int64(48), np.int64(51), np.int64(52), np.int64(54), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(65), np.int64(67), np.int64(68), np.int64(69), np.int64(74), np.int64(75), np.int64(79), np.int64(80)])
valid_clusters: [ 1 65 40 61 30 65 35 60 79 35 21 25 65  2  5 39 24 24 65 40 10 35 24 16
 29 63 74 20 35 34 61 25 61 79 60 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 27 28 29 34 36 38 39 40 41 42 43 44 45]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(27), np.int64(28), np.int64(29), np.int64(34), np.int64(36), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45)])
valid_clusters: [44 41  1 44 10  6  4 21  5  6 22 44 41 19 40  5  7 14 44 14 22 41 45 38
  3 38 44 16  3 24 45  7 16 11 40 44 43  5 44 14 16  7 38 14 27 17  6 38
 16 18 21 43 44 16 16 16  4  2 38 22 22  9 16 20 23 19  5  7 36 40 40 45
 22 24 14  3 21 19 38 15 34 16  1 21 12 14 45 19 44 40 41 16  7  3 14  6
 27 22 40 29 44 12  5 45 39 38  4 19 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 139 142 143 144 145 147 148
 149 150 151 152 153 154 155 156 158 160 162 163 164 165 166 167 169 170
 171 172 173 174 175 176 178 179 180 181 182 183 186 187 188 189 190 191
 192 193 194 195 196 197 198 199 200 201 202 203 205 206 207 209 211 212
 214 215 216 217 218 219 220 222 223 224 225 226 227 228 229 230 231 233
 234 235 236 237 238 239 240 241 242 243 244 245 247 248 249 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 26

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


affinity_propagation, Train accuracy = 0.7981927710843374, Test accuracy = 0.7650602409638554
affinity_propagation, Train f1-score = 0.7968981447934987, Test f1-score = 0.7640597695604986
****************************************************************************************************
Current seed: 43
****************************************************************************************************

____________________________________________________________________________________________________
Classifier: affinity_propagation
43
43


c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  27  28  29  30  31  32  33  34  35  37  38
  40  43  44  45  46  47  48  49  50  51  52  55  56  57  58  60  61  62
  63  64  65  67  72  73  77  78  80  82  83  84  86  87  93  95  97  98
 104 108 109 112 116 117 119 121 124 125 130 134 135 137 140 141 142 146
 147 149 150 151 152 153 154 156 160 163 167 168]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(37), np.int64(38), np.int64(40), np.int64(43), np.int64(44), np.int64(45), np.

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7 8 9]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)])
valid_clusters: [5 2 8 8 7 8 5 6 7 8 3 5 5 2 8 8 5 6 6 1 0 2 7 7 0 4 7 7 0 4 0 0 5 6 0 2 6
 8 6 6 7 6 6 7 4 0 7 5 7 7 7 4 5 8 6 0 0 0 6 7 7 5 5 2 0 4 6 5 0 5 7 0 5 7
 9 0 0 7 4 6 8 7 6 5 6 9 7 6 8 7 0 0 6 6 5 5 6 6 7 7 0 5 7 5 2 8 7 6 6 9 5
 6 0 5 9 7 8 6 0 0 6 3 7 7 6 8 7 2 4 8 8 2 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 19 20 22 27 29 31 32
 37 41]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(19), np.int64(20), np.int64(22), np.int64(27), np.int64(29), np.int64(31), np.int64(32), np.int64(37), np.int64(41)])
valid_clusters: [ 0 41 17 17 10 17 27 32 22 22 22  6 17 16 17 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  11  12  13  14  15  16  17  18
  20  21  22  23  24  25  26  27  29  30  31  32  33  35  37  39  40  41
  42  43  45  46  47  50  51  52  53  54  55  57  60  61  62  63  65  66
  67  69  70  71  72  73  75  77  78  79  80  82  84  89  90  92  93  94
  98  99 101 103 104 106 110 112 115 118 121 122 123 125 127 128]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(35), np.int64(37), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(45), np.int64(46), np.int64(47), np.int64(50), np.int64(51), np.int64(52), np.in

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24)])
valid_clusters: [ 1 18 15  3 23 18  0 21 24 12 16  4 22 23  3 13 14 13 10 11  0  4  5  0
  3 21 23  7  7 14 13  1 14  0 24 15  6  0  4  1 11  4 18 11 18  1  7 10
 24  9 14 12  1 23  1 23  0 12 24 12  1 24  9 23 23 24  8 11  7  7  7 15
  8  1  4 12 21  4 14 11 11  2 14 15  7  1  8  7 24  1  1 24 15  0 23 15
  9  1  4  5 24  1  0 15  7 17  9 18 15  3  0 23 24  7  1  3 12  8 18 15
  3  3 21 10 22  4 23  7  3 24  0 13 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 22 23]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20 21 22 24 25
 26 27 30 31 32 33 34 35 36 37 39 42 44 45 47 48 49 52 54 55 57 58 59 60
 61]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(39), np.int64(42), np.int64(44), np.int64(45), np.int64(47), np.int64(48), np.int64(49), np.int64(52), np.int64(54), np.int64(55), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61)])
valid_clusters: [10 12  1 27 32 27  0 17 32 27 25  6 10 19  1 27  6  7  0 58  9 16 52 20
 12 31 52 20 26  5 13 30  6 61 30 19 61  1 61 37 42 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 23 24
 25 26 28 29 30 31 32 33]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33)])
valid_clusters: [ 1 28 23  4  7  7 14  1 23 10 31 33 32 13 33 24  3 25 28  0  1 10  0 28
 28 31 21 16  0 30  0 18 23  2 24  7  0 14  0 16  0 17  0 14 23 23 23 26
 13 25 16  1  0  4 28 14 32  9 14 23 24 15  3 21 28  0 11 18 23 16  1 16
 33  7 18  1 10 23 18  3 33 23 25 15  7 28 14  1  0 23  8 14 24  5 14  5
  5 10 14 23 13  2  7 28 11 11  0 25 11 21 23 28  7  7 14 18  7 31 18 23
 10 23 24 32 14  2 25 21 33 33 25 33]
[ 0  1  2  3

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  61  62  63  64  67  68  69  70  71  72  73  74
  75  76  78  79  80  81  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
 113 114 115 116 117 119 120 123 124 125 126 127 128 129 130 131 132 134
 135 136 138 140 142 143 144 145 146 147 148 149 151 152 153 154 155 156
 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174
 175 176 177 178 179 181 182 183 184 185 187 188 190 191 192 193 194 195
 196 197 198 199 200 201 202 205 206 207 208 209 210 211 212 213 215 216
 217 218 219 220 221 223 225 226 227 229 230 231 232 234 235 236 237 238
 239 240 241 242 243 244 245 246 247 248 249 251 252 253 254 255 256 258
 259 260 262 263 264 265 266 267 268 269 270 272 27

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 21 22 23 25]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(21), np.int64(22), np.int64(23), np.int64(25)])
valid_clusters: [12  6  6  6 12 25  8 18 18  6 12 12 16  7 18 11 18  6  8  8 12  8  6 10
  8  8 18 25  8 18 18 16 18 12 18 25  6 16  6 18 12 12  7 25 18 25  6  8
  6 18  6 12  7 12 18 10 12  0 18 12 18  6 18 18 18  6 10 12 18  7 18  6
 25 18 18 18 11 25 12 17 11 12  6 18 16  8  6 12 18 16 12 18 18  8 18  8
  6  6 12 18 18  7 17  6 18 25 18  7  6  9 10 18 18  6 13 12  7 15  6 18
 18  7  6 18 13 18  6  6  7  8 25 16  6]
[0 1 2 3 4 5 6]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)])
valid_clusters: [3 5 6 6 3 5 0 5 0 5 6 5

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[0 1 2 3 4 5 6 7 8 9]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)])
valid_clusters: [3 3 1 3 1 8 1 8 7 9 9 1 9 9 7 2 7 3 8 3 3 4 5 2 8 9 1 5 1 8 9 8 4 8 1 2 9
 3 1 7 2 1 1 4 1 3 7 4 3 8 1 5 4 7 1 6 7 6 4 3 5 5 4 9 5 1 2 3 1 7 1 5 8 8
 3 9 2 1 4 5 5 7 2 8 3 1 7 5 9 3 7 1 1 7 8 5 8 4 4 4 8 8 5 5 7 7 3 1 3 7 3
 6 9 3 8 3 7 9 1 1 3 1 8 5 3 3 1 9 1 5 8 4 5]
[ 0  1  2  3  4  6  7  8  9 11 12 13 14 15 17 18 20 21 24 25 27 28 29 30
 32 33 34 35 39 40 42 43 46 47 50 51 54 55 57 59 64]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(17), np.int64(18), np.int64(20), np.int64(21), np.int64(24), np.int64(25), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(32), np.int64(33), np.int64(34), np.

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 20 21 22 23 24 25
 26 27 28 29 31 32 33 34 35 37 38 41 43 44 45 46 47 50 54 55 56 59]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(37), np.int64(38), np.int64(41), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(50), np.int64(54), np.int64(55), np.int64(56), np.int64(59)])
valid_clusters: [17 13  7 38 41 10  6  5 10 44 45  8  6  6 21 12 34  9 10 41 13 21 15  6
 15 38  6  6  8  6 38  6 13 17 10  0 17  6 41 46 38 45  4  8  8 38 45 45
 23  6 20  8 13 25 56 44 45 25 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24)])
valid_clusters: [19  7  5 12 22  6 16 24 21  7 12  0  1  4 14  7  8 20  7  2  2 23 21 24
 19 17 13 23  8  7  7  7  7  2 13 13 21  7  6  8  7 23 19 19 14 23 11  7
 12  9 10  2 11 11 19  7 13  2  5  6 17  6 19 14 14  7 10 19 21 17  7  3
 19  7 16 19  7 22 24 11 21 23  8 22 16  7  6 23 10 14 12 22  2 13 13 12
 22 14 24 21 19  8  8  2  7  5 23  6 17 21  8  7 13  6 13  2  2 13 16  8
 11  5  6 12  8  5 24 13 22 17 12 17  2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
labels_map_cv keys: dict_keys([np.int64(0), np.

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  82  83  84  85  86  87  88  89  90
  92  93  94  95  96  97  98  99 101 102 103 104 106 107 108 109 110 111
 112 113 114 115 116 117 119 120 123 124 126 127 128 129 130 131 132 133
 134 135 136 137 138 139 140 141 142 143 144 145 146 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 166 167 168 169 170 171
 172 173 174 175 176 177 179 180 181 182 183 184 185 186 187 188 189 190
 192 193 194 195 196 197 200 201 202 203 204 205 206 207 208 210 211 212
 213 214 215 216 217 218 219 220 221 222 223 224 227 228 229 231 233 235
 236 237 238 239 240 241 242 243 245 246 248 249 250 252 255 256 258 259
 260 261 263 266 267 268 269 270 271 272 273 274 27

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  82  83  84  85  86  87  88  89  90
  92  93  94  95  96  97  98  99 101 102 103 104 106 107 108 109 110 111
 112 113 114 115 116 117 119 120 124 125 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 167 168 169 170 171 172
 173 174 175 176 177 178 180 181 182 183 184 185 186 187 188 189 190 191
 193 194 195 196 197 198 201 202 203 204 205 206 207 208 209 211 212 213
 214 215 216 217 218 219 220 221 222 223 224 225 228 229 230 232 234 236
 237 238 239 240 241 242 243 244 246 247 249 250 251 253 256 257 259 260
 261 262 264 267 268 269 270 271 272 273 274 275 27

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8 10 11 12 15 16 17 20 21 22 25 26 27 28 30 31
 35 37 38 40 42 45 47 48 49 51 52 53 54 55 56 60 62 66 67 70 71 73 74 76
 78 79 81]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(15), np.int64(16), np.int64(17), np.int64(20), np.int64(21), np.int64(22), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(30), np.int64(31), np.int64(35), np.int64(37), np.int64(38), np.int64(40), np.int64(42), np.int64(45), np.int64(47), np.int64(48), np.int64(49), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(60), np.int64(62), np.int64(66), np.int64(67), np.int64(70), np.int64(71), np.int64(73), np.int64(74), np.int64(76), np.int64(78), np.int64(79), np.int64(81)])
valid_clusters: [52 73 12  1 53 10 16 73 53 12 21 53 53 51 55 52 17 73 52 27 53 53 76 53
 49 73 12  7 53 5

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  24  26  28  30  31  32  33  34  36  37  38  39  40  41  42
  44  46  48  51  53  54  55  56  58  59  61  64  66  68  71  72  78  79
  81  82  85  88  90  91  92  95  96 101 107 112]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(24), np.int64(26), np.int64(28), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(44), np.int64(46), np.int64(48), np.int64(51), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(58), np.int64(59), np.int64(61), np.int64(64), np.int64(66), np.int64(68), np.int64(7

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 16 17 18 19 22 23]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(22), np.int64(23)])
valid_clusters: [23  7 17 18  0 12  2 12 18  2 17 17 18  1 12 17  0 23 23 23  4  2 23  0
  1 23 23  2 18 23 12 16 17  0 23  1  7 18  5 13  0 23 22 12 18 13 17  6
  1 17  1 13 18 18 18  1 18  0 22 18  2  5 18 23  2 22 22 23  1  8 17  1
 17 23 14  0 18 12 23 14  1  0 18 14  0 13 23 17  5  1  8 18  0  0 17 18
  7 17 18 17 18 17 18  2 22 23  1  2 17 19 22 23 12  0 18 18 18 23 18 23
  2 17 13 22 18 17 22 18 17  0  5 17]
[0 1 2 3 4 5 6 7 8]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)])
valid_clusters: [3 6 4 1 7 4 3 6 5 4 1 7 7 6 7 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(
c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25)])
valid_clusters: [ 0 11 13 25  1  7 19 16  6 18  7 13 25 23  6  5 25 11 25  2 13 15  3 18
  0 13  7 19  7 15  1  6 18 25 11 16 18 20  3  7  7  6 23  2  2  5  2 11
  2  6 24 25 25  1 15  6 22  7 12 17  9  2  3 15 18  2  8 22 20 25 20 20
 14  3 16 12 12 12 11 10 21  8 20 18  7  1  2  3 11 19 18  2 18 14 12  1
 19  1 12  2  0 15 22  2 13 11  8 16  3 16  7  8  3 18  6  2 13 22  7  8
 13  3 10 19 20  3  3  5 25 25 20 25  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
labels_map_cv keys: dict_keys([np.int64(

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[ 0  1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18 19 20 21 23 24 25 26
 27 28 29 31 33 34 36 37 38 39]
labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(31), np.int64(33), np.int64(34), np.int64(36), np.int64(37), np.int64(38), np.int64(39)])
valid_clusters: [34  3 16 31  2 26  4 26 31  8 21 16 36 31  6 21  2  0  0 34 17  8 16 14
 13 34  0  8 31 34 25 29  0 14 16  5 33 16 23  8 14 34 12 26 31  1 16 17
  5 16  5 24 36 36 31 13 31 39 28 37  8 38 31 16  8 27 12  0 16  8 21 13
 39 16  4  2 34 26  0 29 19  2 36  4 14  1 34 16 27  5  8 36  2  2 16 31
 33 39 37 16 31 16 37  8 12 34  5 37 21 17 28 34 26  2 31 36 34 34 21  0
 19  0 24 12 21 

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(69), np.int64(70), np.int64(71),

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


labels_map_cv keys: dict_keys([np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69),

c:\Users\britt\anaconda3\envs\AppliedAILabs\Lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning: Affinity propagation did not converge, this model may return degenerate cluster centers and labels.
  warnings.warn(


[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  58  59  60  61  62  63  64  65  66  67  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  95  96  97  98 100 101 102 104 105 106 107 109 110 111 112 114
 115 116 118 119 120 121 122 123 124 125 126 127 128 129 130 132 133 134
 135 136 137 138 139 140 141 142 143 145 146 148 149 151 152 153 154 155
 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173
 174 175 176 177 178 179 181 182 183 185 186 187 188 189 191 192 193 195
 196 197 198 199 200 201 203 204 205 206 207 208 209 210 211 213 214 215
 216 217 218 220 222 223 224 225 227 228 229 230 231 232 233 234 235 236
 237 238 239 240 241 242 243 244 245 247 248 250 251 252 253 254 255 256
 257 258 259 260 261 262 263 264 265 266 267 269 27

In [14]:
rank_counter = 0
print(f"{'Rank':<5} {'Classifier':<30} {'Avg. test acc.':<17} {'Avg. train acc.':<17} {'Avg. test F1':<17} {'Avg train F1':<17}")
print("_"*100)
for i, clf in enumerate(sorted(metrics_dict["test_acc_avg"].items(), key=lambda x: x[1], reverse=True)):
    if clf[0].endswith("count"):
        rank_counter += 1
        continue
    print(f"{i+1-rank_counter:<5} {clf[0][:-4]:<30} {clf[1]:<17.3f} {metrics_dict['train_acc_avg'][clf[0]]:<8.3f}\
          {metrics_dict['test_f1_avg'][clf[0]]:<18.3f}{metrics_dict['train_f1_avg'][clf[0]]:<17.3f}")
print("_"*100)

Rank  Classifier                     Avg. test acc.    Avg. train acc.   Avg. test F1      Avg train F1     
____________________________________________________________________________________________________
1     affinity_propagation           0.771             0.830             0.771             0.830            
____________________________________________________________________________________________________
